# Alembic Configuration
# path to migration files
[alembic]
sqlalchemy.url = driver://user:pass@localhost/dbname

# use relative paths, so migrations work regardless of current working dir
prepend_sys_path = .

# timezone to assume when rendering the date within the migration file as code
# string value is passed to dateutil.tz.gettz()
# None to render as local datetime
sqlalchemy.timezone =

# max length of characters to apply to the
# "slug" field in migration message
# set to empty string to disable, but migrations created
# after this change will not verify against unicode characters.
mako.input_encoding = utf-8

