export const ROUTES = {
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  SYSTEMS: "/systems",
  HISTORY: "/history",
  TENANTS: "/tenants",
  USERS: "/users",
  ALERTS: "/alerts",
  AUTOMATION: "/automation",
  LOGS: "/logs",
  RELIABILITY: "/reliability",
  AI: "/ai",
  RELEASES: "/releases",
  UPDATES: "/updates",
  REMOTE: "/remote",
  PLATFORM: "/platform",
  BACKUP: "/backup",
  AUDIT: "/audit",
} as const;
