import { PERMISSIONS } from "./permissions";
import { ROUTES } from "./routes";

export const ROUTE_PERMISSIONS = {
  [ROUTES.DASHBOARD]: PERMISSIONS.DASHBOARD_VIEW,
  [ROUTES.SYSTEMS]: PERMISSIONS.DASHBOARD_VIEW,
  [ROUTES.HISTORY]: PERMISSIONS.AUTOMATION_MANAGE,
  [ROUTES.TENANTS]: PERMISSIONS.TENANT_MANAGE,
  [ROUTES.INCIDENTS]: PERMISSIONS.AUTOMATION_MANAGE,
  [ROUTES.USERS]: PERMISSIONS.TENANT_MANAGE,
  [ROUTES.ALERTS]: PERMISSIONS.AUTOMATION_MANAGE,
  [ROUTES.AUTOMATION]: PERMISSIONS.AUTOMATION_MANAGE,
  [ROUTES.LOGS]: PERMISSIONS.AUTOMATION_MANAGE,
  [ROUTES.RELIABILITY]: PERMISSIONS.AUTOMATION_MANAGE,
  [ROUTES.AI]: PERMISSIONS.AUTOMATION_MANAGE,
  [ROUTES.RELEASES]: PERMISSIONS.DASHBOARD_VIEW,
  [ROUTES.UPDATES]: PERMISSIONS.AUTOMATION_MANAGE,
  [ROUTES.REMOTE]: PERMISSIONS.AUTOMATION_MANAGE,
  [ROUTES.AGENT_COMMANDS]: PERMISSIONS.AUTOMATION_MANAGE,
  [ROUTES.PLATFORM]: PERMISSIONS.TENANT_MANAGE,
  [ROUTES.BACKUP_DRILL]: PERMISSIONS.BACKUP_MANAGE,
  [ROUTES.TENANT_SETTINGS]: PERMISSIONS.TENANT_MANAGE,
  [ROUTES.TENANT_CONTROLS]: PERMISSIONS.TENANT_MANAGE,
  [ROUTES.TENANT_QUOTAS]: PERMISSIONS.TENANT_MANAGE,
  [ROUTES.TENANT_COMMERCIAL]: PERMISSIONS.TENANT_MANAGE,
  [ROUTES.OIDC_PROVIDERS]: PERMISSIONS.TENANT_MANAGE,
  [ROUTES.TENANT_SECRETS]: PERMISSIONS.TENANT_MANAGE,
  [ROUTES.AGENT_ENROLLMENT]: PERMISSIONS.TENANT_MANAGE,
  [ROUTES.BACKUP]: PERMISSIONS.BACKUP_MANAGE,
  [ROUTES.AUDIT]: PERMISSIONS.TENANT_MANAGE,
} as const;

export type GuardedRoute = keyof typeof ROUTE_PERMISSIONS;
