"""Agent release management service.

Supports server-side storage of versioned Windows agent artifacts and
portal/API-friendly listing + download access.
"""

from __future__ import annotations

import os
import re
import json
import shutil
import subprocess
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

from werkzeug.utils import secure_filename


@dataclass
class AgentRelease:
    filename: str
    version: str
    size_bytes: int
    modified_at: str

    def to_dict(self) -> dict[str, Any]:
        return {
            'filename': self.filename,
            'version': self.version,
            'size_bytes': self.size_bytes,
            'modified_at': self.modified_at,
        }


class AgentReleaseService:
    """Manage release artifact directory and metadata extraction."""

    RELEASE_PATTERN = re.compile(r'^aaditech-agent-([A-Za-z0-9._-]+)\.exe$')
    POLICY_FILENAME = 'release_policy.json'
    BUILT_BINARY_BASENAME = 'aaditech-agent'

    @classmethod
    def _resolve_built_binary_candidates(cls, root_path: str) -> list[Path]:
        dist_dir = Path(root_path).resolve().parent / 'agent' / 'dist'
        base = dist_dir / cls.BUILT_BINARY_BASENAME
        candidates: list[Path] = [base, base.with_suffix('.exe')]

        # Include any variant generated by PyInstaller for robustness across platforms.
        if dist_dir.exists() and dist_dir.is_dir():
            for item in dist_dir.glob(f'{cls.BUILT_BINARY_BASENAME}*'):
                if item not in candidates:
                    candidates.append(item)

        return candidates

    @classmethod
    def resolve_built_binary_path(cls, root_path: str) -> Path:
        candidates = cls._resolve_built_binary_candidates(root_path)
        existing_files = [candidate for candidate in candidates if candidate.exists() and candidate.is_file()]
        if existing_files:
            # Prefer latest modified artifact when multiple variants exist.
            existing_files.sort(key=lambda p: p.stat().st_mtime, reverse=True)
            return existing_files[0]

        # Fallback path used when no artifact exists yet.
        return candidates[0]

    @classmethod
    def resolve_build_spec_path(cls, root_path: str) -> Path:
        return Path(root_path).resolve().parent / 'agent' / 'build.spec'

    @classmethod
    def build_agent_binary(cls, root_path: str, timeout_seconds: int = 180) -> dict[str, Any]:
        spec_path = cls.resolve_build_spec_path(root_path)
        dist_path = spec_path.parent / 'dist'
        work_path = spec_path.parent / 'build'

        if not spec_path.exists() or not spec_path.is_file():
            return {
                'success': False,
                'reason': 'spec_not_found',
                'details': str(spec_path),
            }

        try:
            completed = subprocess.run(
                [
                    'pyinstaller',
                    '--distpath',
                    str(dist_path),
                    '--workpath',
                    str(work_path),
                    '--noconfirm',
                    str(spec_path),
                ],
                check=False,
                capture_output=True,
                text=True,
                timeout=timeout_seconds,
            )
        except FileNotFoundError:
            return {
                'success': False,
                'reason': 'pyinstaller_missing',
                'details': 'pyinstaller executable not found',
            }
        except subprocess.TimeoutExpired:
            return {
                'success': False,
                'reason': 'build_timeout',
                'details': f'timeout after {timeout_seconds} seconds',
            }

        binary_path = cls.resolve_built_binary_path(root_path)
        binary_exists = binary_path.exists() and binary_path.is_file()
        return {
            'success': completed.returncode == 0 and binary_exists,
            'returncode': int(completed.returncode),
            'binary_available': bool(binary_exists),
            'binary_path': str(binary_path),
            'stdout_tail': (completed.stdout or '')[-800:],
            'stderr_tail': (completed.stderr or '')[-800:],
        }

    @classmethod
    def _resolve_release_dir(cls, config: dict[str, Any], instance_path: str) -> Path:
        configured = str(config.get('AGENT_RELEASES_DIR', '')).strip()
        if not configured:
            return Path(instance_path) / 'agent_releases'

        path = Path(configured)
        if path.is_absolute():
            return path
        return Path(instance_path) / path

    @classmethod
    def ensure_release_dir(cls, config: dict[str, Any], instance_path: str) -> Path:
        release_dir = cls._resolve_release_dir(config, instance_path)
        release_dir.mkdir(parents=True, exist_ok=True)
        return release_dir

    @classmethod
    def _extract_version(cls, filename: str) -> str:
        match = cls.RELEASE_PATTERN.match(filename)
        if match:
            return match.group(1)
        return 'unknown'

    @classmethod
    def list_releases(cls, config: dict[str, Any], instance_path: str) -> list[AgentRelease]:
        release_dir = cls.ensure_release_dir(config, instance_path)
        releases: list[AgentRelease] = []
        for item in release_dir.iterdir():
            if not item.is_file():
                continue
            if item.suffix.lower() != '.exe':
                continue

            stat = item.stat()
            releases.append(
                AgentRelease(
                    filename=item.name,
                    version=cls._extract_version(item.name),
                    size_bytes=int(stat.st_size),
                    modified_at=datetime.fromtimestamp(stat.st_mtime).isoformat(),
                )
            )

        releases.sort(key=lambda rel: rel.modified_at, reverse=True)
        return releases

    @classmethod
    def save_uploaded_release(
        cls,
        uploaded_file,
        version: str,
        config: dict[str, Any],
        instance_path: str,
    ) -> AgentRelease:
        release_dir = cls.ensure_release_dir(config, instance_path)

        version = str(version or '').strip()
        if not version:
            raise ValueError('version_required')
        if not re.fullmatch(r'[A-Za-z0-9._-]{1,64}', version):
            raise ValueError('version_invalid')

        original_name = secure_filename(uploaded_file.filename or '')
        if not original_name.lower().endswith('.exe'):
            raise ValueError('only_exe_allowed')

        target_name = f'aaditech-agent-{version}.exe'
        target_path = release_dir / target_name
        uploaded_file.save(target_path)

        stat = target_path.stat()
        return AgentRelease(
            filename=target_name,
            version=version,
            size_bytes=int(stat.st_size),
            modified_at=datetime.fromtimestamp(stat.st_mtime).isoformat(),
        )

    @classmethod
    def register_release_file(
        cls,
        source_path: str,
        version: str,
        config: dict[str, Any],
        instance_path: str,
    ) -> AgentRelease:
        release_dir = cls.ensure_release_dir(config, instance_path)

        source = Path(source_path)
        if not source.exists() or not source.is_file():
            raise ValueError('source_not_found')
        if source.suffix.lower() != '.exe':
            raise ValueError('source_not_exe')

        version = str(version or '').strip()
        if not version or not re.fullmatch(r'[A-Za-z0-9._-]{1,64}', version):
            raise ValueError('version_invalid')

        target_name = f'aaditech-agent-{version}.exe'
        target_path = release_dir / target_name
        shutil.copyfile(source, target_path)

        stat = target_path.stat()
        return AgentRelease(
            filename=target_name,
            version=version,
            size_bytes=int(stat.st_size),
            modified_at=datetime.fromtimestamp(stat.st_mtime).isoformat(),
        )

    @classmethod
    def resolve_download_path(
        cls,
        filename: str,
        config: dict[str, Any],
        instance_path: str,
    ) -> Path | None:
        release_dir = cls.ensure_release_dir(config, instance_path)
        safe_name = secure_filename(filename or '')
        if not safe_name or os.path.sep in safe_name or safe_name.startswith('.'):
            return None

        file_path = release_dir / safe_name
        if not file_path.exists() or not file_path.is_file():
            return None
        return file_path

    @classmethod
    def _policy_path(cls, config: dict[str, Any], instance_path: str) -> Path:
        release_dir = cls.ensure_release_dir(config, instance_path)
        return release_dir / cls.POLICY_FILENAME

    @classmethod
    def get_policy(cls, config: dict[str, Any], instance_path: str) -> dict[str, Any]:
        path = cls._policy_path(config, instance_path)
        if not path.exists() or not path.is_file():
            return {
                'target_version': '',
                'notes': '',
                'updated_at': None,
            }

        try:
            payload = json.loads(path.read_text(encoding='utf-8'))
        except Exception:
            return {
                'target_version': '',
                'notes': '',
                'updated_at': None,
            }

        return {
            'target_version': str(payload.get('target_version') or '').strip(),
            'notes': str(payload.get('notes') or '').strip(),
            'updated_at': payload.get('updated_at'),
        }

    @classmethod
    def set_policy(
        cls,
        target_version: str,
        notes: str,
        config: dict[str, Any],
        instance_path: str,
    ) -> dict[str, Any]:
        releases = cls.list_releases(config, instance_path)
        known_versions = {release.version for release in releases}

        cleaned_target = str(target_version or '').strip()
        if cleaned_target and cleaned_target not in known_versions:
            raise ValueError('target_version_not_found')

        policy = {
            'target_version': cleaned_target,
            'notes': str(notes or '').strip(),
            'updated_at': datetime.utcnow().isoformat(),
        }

        path = cls._policy_path(config, instance_path)
        path.write_text(json.dumps(policy, indent=2), encoding='utf-8')
        return policy

    @classmethod
    def _version_key(cls, value: str) -> tuple:
        # Build a sortable key for versions like 1.2.3, 1.2.3-beta, etc.
        chunks = re.split(r'([0-9]+)', str(value or '').strip())
        key: list[Any] = []
        for chunk in chunks:
            if chunk == '':
                continue
            if chunk.isdigit():
                key.append((0, int(chunk)))
            else:
                key.append((1, chunk.lower()))
        return tuple(key)

    @classmethod
    def build_update_guide(
        cls,
        current_version: str,
        config: dict[str, Any],
        instance_path: str,
    ) -> dict[str, Any]:
        releases = cls.list_releases(config, instance_path)
        if not releases:
            return {
                'status': 'no_releases',
                'current_version': str(current_version or '').strip(),
                'recommended_version': None,
                'action': 'none',
                'latest_version': None,
                'downgrade_candidates': [],
                'releases': [],
                'policy': cls.get_policy(config, instance_path),
            }

        sorted_by_version = sorted(releases, key=lambda rel: cls._version_key(rel.version), reverse=True)
        known_versions = {release.version for release in releases}

        latest_version = sorted_by_version[0].version
        policy = cls.get_policy(config, instance_path)
        configured_target = str(policy.get('target_version') or '').strip()
        recommended_version = configured_target if configured_target in known_versions else latest_version

        current_clean = str(current_version or '').strip()
        action = 'none'
        if current_clean:
            if cls._version_key(current_clean) < cls._version_key(recommended_version):
                action = 'upgrade'
            elif cls._version_key(current_clean) > cls._version_key(recommended_version):
                action = 'downgrade'

        downgrade_candidates = [
            release.to_dict()
            for release in sorted_by_version
            if cls._version_key(release.version) < cls._version_key(recommended_version)
        ]

        return {
            'status': 'ok',
            'current_version': current_clean,
            'recommended_version': recommended_version,
            'action': action,
            'latest_version': latest_version,
            'downgrade_candidates': downgrade_candidates,
            'releases': [release.to_dict() for release in sorted_by_version],
            'policy': policy,
        }
