export const queryKeys = {
  me: ["auth", "me"] as const,
  dashboard: ["dashboard"] as const,
  dashboardStatus: (hostName: string) => ["dashboard", "status", hostName] as const,
  apiStatus: ["platform", "api-status"] as const,
  systems: ["systems"] as const,
  system: (id: number) => ["systems", id] as const,
  tenants: ["tenants"] as const,
  tenantSettings: ["tenants", "settings"] as const,
  tenantControls: ["tenants", "controls"] as const,
  tenantQuotas: ["tenants", "quotas"] as const,
  tenantUsage: ["tenants", "usage"] as const,
  tenantUsageReport: ["tenants", "usage-report"] as const,
  tenantCommercial: ["tenants", "commercial"] as const,
  oidcProviders: ["auth", "oidc", "providers"] as const,
  myTotp: ["auth", "mfa", "totp"] as const,
  alerts: ["alerts"] as const,
  alertDeliveryHistory: ["alerts", "delivery-history"] as const,
  incidents: ["incidents"] as const,
  incidentComments: (incidentId: number) => ["incidents", incidentId, "comments"] as const,
  automation: ["automation"] as const,
  workflowRuns: ["automation", "workflow-runs"] as const,
  operationsTimeline: ["operations", "timeline"] as const,
  aiOperationsReport: ["ai", "operations", "report"] as const,
  logSources: ["logs", "sources"] as const,
  logInvestigations: ["logs", "investigations"] as const,
  logSource: (id: number) => ["logs", "sources", id] as const,
  logEntries: ["logs", "entries"] as const,
  logEntry: (id: number) => ["logs", "entries", id] as const,
  reliabilityRuns: ["reliability", "runs"] as const,
  reliabilityRun: (id: number) => ["reliability", "runs", id] as const,
  updateRuns: ["updates", "runs"] as const,
  updateRun: (id: number) => ["updates", "runs", id] as const,
  releases: ["releases"] as const,
  releasePolicy: ["releases", "policy"] as const,
  releaseGuide: (version: string) => ["releases", "guide", version] as const,
};
